const QUERIES = {
  DRAFTS: {
    GET: 'QUERY_GET_DRAFTS',
  },
  SCHEDULES: {
    GET: 'QUERY_GET_SCHEDULES',
  },
  NOTIFICATIONS: {
    GET: 'QERUY_GET_NOTIFICATIONS',
  },
  SNIPPETS: {
    GET: 'QUERY_GET_SNIPPETS',
  },
  MEDIA: {
    GET: 'QUERY_GET_UPLOADS',
  },
  WALLET: {
    GET: 'QUERY_GET_ASSETS',
    UNCLAIMED_GET: 'QUERY_GET_UNCLAIMED'
  },
};

export default QUERIES;
