import EStyleSheet from 'react-native-extended-stylesheet';

export default EStyleSheet.create({
  post: {
    shadowColor: '$white',
    padding: 0,
    marginRight: 0,
    marginLeft: 0,
    marginTop: 10,
    marginBottom: 0,
    borderRadius: 5,
    backgroundColor: '$primaryBackgroundColor',
  },
  avatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderColor: 'lightgray',
    borderWidth: 1,
  },
  author: {
    backgroundColor: '$white',
    alignSelf: 'flex-start',
    paddingVertical: 5,
  },
  timeAgo: {
    alignSelf: 'center',
    fontSize: 9,
    fontWeight: '100',
    marginHorizontal: 3,
  },
  authorName: {
    color: '#222',
    fontWeight: '600',
    fontSize: 10,
  },
  upvoteButton: {
    margin: 0,
    flexDirection: 'row',
    paddingVertical: 0,
  },
  upvoteIcon: {
    alignSelf: 'flex-start',
    fontSize: 20,
    color: '#007ee5',
    margin: 0,
    width: 18,
  },
  payout: {
    alignSelf: 'center',
    fontSize: 10,
    color: '#626262',
    marginLeft: 3,
  },
  payoutButton: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    paddingVertical: 2,
  },
  commentButton: {
    padding: 0,
    margin: 0,
    flexDirection: 'row',
  },
  comment: {
    alignSelf: 'center',
    fontSize: 10,
    marginLeft: 3,
    color: '$iconColor',
  },
  commentIcon: {
    alignSelf: 'flex-start',
    fontSize: 20,
    color: '$iconColor',
    margin: 0,
    width: 20,
  },

  header: {
    shadowColor: '$white',
    height: 50,
    borderRadius: 5,
    backgroundColor: '$primaryBackgroundColor',
  },
  body: {
    justifyContent: 'flex-start',
    flexDirection: 'row',
    backgroundColor: '$primaryBackgroundColor',
  },
  text: {
    fontSize: 7,
    alignSelf: 'center',
    textAlignVertical: 'center',
    color: '$white',
    fontWeight: 'bold',
  },
  topLikers: {
    marginHorizontal: 16,
    flexDirection: 'row',
    height: 30,
    borderRadius: 5,
  },
  likersWrapper: {
    backgroundColor: '$primaryLightBackground',
    shadowColor: '$white',
  },
  liker: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 0.5,
    alignSelf: 'center',
    borderColor: 'lightgray',
    marginVertical: -5,
  },
  footer: {
    shadowColor: '$white',
    paddingLeft: 5,
    borderRadius: 5,
    fontSize: 10,
    fontWeight: '100',
    alignSelf: 'center',
    fontFamily: '$primaryFont',
    color: '$primaryDarkGray',
  },
  popover: {
    width: '$deviceWidth - 20',
    borderRadius: 5,
    padding: 10,
  },
  track: {
    height: 2,
    borderRadius: 1,
  },
  thumb: {
    width: 30,
    height: 30,
    borderRadius: 30 / 2,
    backgroundColor: '$primaryBackgroundColor',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 2,
    shadowOpacity: 0.35,
    elevation: 3,
  },
  postBodyWrapper: {
    marginHorizontal: 9,
  },
  image: {
    margin: 0,
    alignItems: 'center',
    alignSelf: 'center',
    height: 200,
    width: '$deviceWidth - 16',
    borderRadius: 8,
    backgroundColor: '$primaryLightGray',
  },
  postDescripton: {
    flexDirection: 'column',
    paddingHorizontal: 8,
    backgroundColor: '$primaryBackgroundColor',
  },
  title: {
    fontSize: 14,
    fontWeight: 'bold',
    marginVertical: 12,
    color: '$primaryBlack',
  },
  summary: {
    fontSize: 12,
    fontWeight: '200',
    overflow: 'hidden',
    color: '$primaryDarkGray',
  },
  bodyFooter: {
    backgroundColor: '$primaryBackgroundColor',
    flexDirection: 'row',
    margin: 16,
    justifyContent: 'space-between',
  },
  bodyHeader: {
    backgroundColor: '$primaryBackgroundColor',
    flexDirection: 'row',
    marginHorizontal: 12,
    marginBottom: 12,
  },
  leftFooterWrapper: {
    flexDirection: 'row',
  },
  dropdownWrapper: {
    position: 'absolute',
    right: -10,
  },
});
