import applyWrapFormat from './applyWrapFormat';
import applyWrapFormatNewLines from './applyWrapFormatNewLines';
import applyListFormat from './applyListFormat';
import applyWebLinkFormat from './applyWebLinkFormat';

export default [
  {
    key: 'B',
    title: 'B',
    icon: 'bold',
    iconType: 'Feather',
    wrapper: '**',
    onPress: applyWrapFormat,
    // style: { fontWeight: 'bold' },
  },
  {
    key: 'I',
    title: 'I',
    icon: 'italic',
    iconType: 'Feather',
    wrapper: '*',
    onPress: applyWrapFormat,
  },
  {
    key: 'U',
    title: 'U',
    icon: 'underline',
    iconType: 'Feather',
    wrapper: '__',
    onPress: applyWrapFormat,
  },
  {
    key: 'S',
    title: 'S',
    wrapper: '~~',
    icon: 'strikethrough',
    iconType: 'FontAwesome',
    onPress: applyWrapFormat,
  },
  {
    key: '>',
    title: '>',
    prefix: '>',
    icon: 'ios-quote',
    onPress: applyListFormat,
  },
  {
    key: 'C',
    title: 'C',
    icon: 'code',
    iconType: 'Feather',
    wrapper: '`',
    onPress: applyWrapFormat,
  },
  {
    key: 'CC',
    title: 'CC',
    icon: 'ios-code-working',
    wrapper: '```',
    onPress: applyWrapFormatNewLines,
  },
  {
    key: 'L',
    title: 'L',
    icon: 'list',
    iconType: 'Feather',
    prefix: '-',
    onPress: applyListFormat,
  },
  {
    key: 'WEB',
    title: 'WEB',
    icon: 'link-2',
    iconType: 'Feather',
    onPress: applyWebLinkFormat,
  },
  {
    key: 'H1',
    title: 'H1',
    icon: 'format-size',
    iconType: 'MaterialCommunityIcons',
    prefix: '#',
    onPress: applyListFormat,
  },
  {
    key: 'H2',
    title: 'H2',
    prefix: '##',
    onPress: applyListFormat,
  },
  {
    key: 'H3',
    title: 'H3',
    prefix: '###',
    onPress: applyListFormat,
  },
  {
    key: 'H4',
    title: 'H4',
    prefix: '####',
    onPress: applyListFormat,
  },
  {
    key: 'H5',
    title: 'H5',
    prefix: '#####',
    onPress: applyListFormat,
  },
  {
    key: 'H6',
    title: 'H6',
    prefix: '######',
    onPress: applyListFormat,
  },
];
