export default [
  'cross-post',
  'promote',
  'copy',
  'reply',
  'translate',
  'reblog',
  'undo-reblog',
  'pin-blog',
  'unpin-blog',
  'pin-community',
  'unpin-community',
  'pin-reply',
  'unpin-reply',
  'edit-history',
  'share',
  'bookmarks',
  'mute',
  'report',
  'delete-post',
] as const;
