# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eSteem' do
  pod 'AppCenter/Push'
  pod 'AppCenter/Crashes'
  pod 'AppCenter/Analytics'
  pod 'AppCenterReactNativeShared'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eSteem
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTImage' # <- Add this line
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  

  platform :ios, '8.0'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  target 'eSteemTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'eSteem-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eSteem-tvOS

  target 'eSteem-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
