export default (accountData = {}) => {
  const persistData = {};

  Object.assign(persistData, {
    about: accountData.about,
    active: accountData.active,
    avatar: accountData.avatar,
    balance: accountData.balance,
    can_vote: accountData.can_vote,
    comment_count: accountData.comment_count,
    created: accountData.created,
    delegated_hive_power: accountData.delegated_hive_power,
    delegated_vesting_shares: accountData.delegated_vesting_shares,
    display_name: accountData.display_name,
    downvote_manabar: accountData.downvote_manabar,
    hbd_balance: accountData.hbd_balance,
    id: accountData.id,
    json_metadata: accountData.json_metadata,
    local: accountData.local,
    memo_key: accountData.memo_key,
    name: accountData.name,
    next_vesting_withdrawal: accountData.next_vesting_withdrawal,
    owner: accountData.owner,
    password: accountData.password,
    post_count: accountData.post_count,
    posting: accountData.posting,
    posting_json_metadata: accountData.posting_json_metadata,
    rc_manabar: accountData.rc_manabar,
    received_hive_power: accountData.received_hive_power,
    received_vesting_shares: accountData.received_vesting_shares,
    reputation: accountData.reputation,
    reward_hbd_balance: accountData.reward_hbd_balance,
    reward_hive_balance: accountData.reward_hive_balance,
    reward_vesting_balance: accountData.reward_vesting_balance,
    reward_vesting_hive: accountData.reward_vesting_hive,
    savings_balance: accountData.savings_balance,
    savings_hbd_balance: accountData.savings_hbd_balance,
    savings_hbd_seconds: accountData.savings_hbd_seconds,
    savings_withdraw_requests: accountData.savings_withdraw_requests,
    hive_power: accountData.hive_power,
    to_withdraw: accountData.to_withdraw,
    unread_activity_count: accountData.unread_activity_count,
    username: accountData.username,
    vesting_balance: accountData.vesting_balance,
    vesting_shares: accountData.vesting_shares,
    vesting_withdraw_rate: accountData.vesting_withdraw_rate,
    voting_manabar: accountData.voting_manabar,
    voting_power: accountData.voting_power,
    vp_manabar: accountData.vp_manabar,
    withdraw_routes: accountData.withdraw_routes,
    withdrawn: accountData.withdrawn,
  });

  return persistData;
};
