export const orientations = {
  PORTRAIT: 'PORTRAIT',
  LANDSCAPE_LEFT: 'LANDSCAPE-LEFT',
  LANDSCAPE_RIGHT: 'LANDSCAPE-RIGHT',
  PORTRAIT_UPSIDEDOWN: 'PORTRAIT-UPSIDEDOWN',
  UNKNOWN: 'UNKNOWN',
  LANDSCAPE: 'LANDSCAPE',
};
