import EStyleSheet from 'react-native-extended-stylesheet';

export default EStyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '$primaryBackgroundColor',
    justifyContent: 'center',
  },
  balanceText: {
    fontSize: 14,
    color: '$primaryDarkGray',
    alignSelf: 'center',
    marginLeft: 20,
    marginBottom: 10,
  },
  descText: {
    fontSize: 14,
    color: '$primaryDarkGray',
    alignSelf: 'center',
    marginLeft: 10,
    marginBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  topContent: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  middleContent: {
    flex: 3,
    justifyContent: 'center',
  },
  bottomContent: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: -1,
  },
  input: {
    borderWidth: 1,
    borderColor: '$borderColor',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    color: '$primaryBlack',
    width: 172,
  },
  autocomplate: {
    borderWidth: 0,
    borderColor: '$borderColor',
    borderRadius: 8,
    padding: 2,
    width: 172,
    marginRight: 33,
  },
  autocomplateLineContainer: {
    flexDirection: 'row',
    zIndex: 999,
  },
  autocomplateLabelText: {
    color: '$primaryBlack',
    fontWeight: '600',
    textAlign: 'left',
  },
  autocomplateListContainer: {
    backgroundColor: '$primaryWhiteLightBackground',
    width: 172,
    zIndex: 999,
  },
  autocomplateItemText: {
    color: '$primaryBlack',
    padding: 3,
  },
  autocomplateList: {
    zIndex: 999,
    backgroundColor: '$primaryWhiteLightBackground',
  },
  autocomplateLabelContainer: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    justifyContent: 'center',
    color: '$primaryBlack',
    maxWidth: '$deviceWidth / 2.9',
  },
  textarea: {
    borderWidth: 1,
    borderColor: '$borderColor',
    borderRadius: 8,
    padding: 10,
    color: '$primaryBlack',
    width: 172,
    height: 75,
  },
  expiryDate: {
    color: '$iconColor',
    alignSelf: 'center',
    fontSize: 16,
    marginTop: 16,
  },
  button: {
    width: '$deviceWidth / 3',
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
  },
  icon: {
    fontSize: 40,
    color: '$iconColor',
    marginHorizontal: 20,
  },
  rowTextStyle: {
    fontSize: 12,
    color: '$primaryDarkGray',
    padding: 5,
  },
  dropdownText: {
    fontSize: 14,
    paddingLeft: 12,
    paddingHorizontal: 14,
    color: '$primaryDarkGray',
  },
  dropdownStyle: {
    marginTop: 15,
    minWidth: 192,
    width: 192,
    maxHeight: '$deviceHeight - 200',
  },
  dropdownButtonStyle: {
    borderColor: '$borderColor',
    borderWidth: 1,
    height: 44,
    width: 172,
    borderRadius: 8,
    marginHorizontal: 2,
  },
  dropdown: {
    flexGrow: 1,
    width: 130,
  },
  slider: {
    flex: 1,
    marginHorizontal: 30,
  },
  amountText: {
    color: '$primaryBlue',
  },
  iconButton: {
    borderColor: 'red',
    borderWidth: 1,
    width: 25,
    height: 25,
    borderRadius: 5,
  },
  total: {
    marginVertical: 15,
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  day: {
    fontSize: 22,
    color: '$primaryBlue',
    fontWeight: 'bold',
  },
  price: {
    fontSize: 15,
    color: '$primaryBlue',
  },
  separator: {
    margin: 15,
    height: 1,
    width: '$deviceWidth/1.1',
    backgroundColor: '$primaryDarkGray',
  },
});
